name: Deploy Backend to Azure Web App

on:
  push:
    branches: [ updated-version, main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies and create deployment package
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        zip -r ../backend-package.zip *
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cubits'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend-package.zip'
